// Anne Frank - The Diary Of A Young Girl

const sentences = [
  `On Friday, June 12, I was awake at six o'clock, which isn't surprising, since it was my birthday. But I'm not allowed to get up at that hour, so I had to control my curiosity until quarter to seven. When I couldn't wait any longer, I went to the dining room, where Moortje (the cat) welcomed me by rubbing against my legs.`,

  `A little after seven I went to Daddy and Mama and then to the living room to open my presents, and you were the first thing I saw, maybe one of my nicest presents. Then a bouquet of roses, some peonies and a potted plant. From Daddy and Mama I got a blue blouse, a game, a bottle of grape juice, which to my mind tastes a bit like wine (after all, wine is made from grapes), a puzzle, a jar of cold cream, 2.50 guilders and a gift certificate for two books.`,

  `I got another book as well, Camera Obscura (but Margot already has it, so I exchanged mine for something else), a platter of homemade cookies (which I made myself, of course, since I've become quite an expert at baking cookies), lots of candy and a strawberry tart from Mother. And a letter from Grammy, right on time, but of course that was just a coincidence.`,

  `Then Hanneli came to pick me up, and we went to school. During recess I passed out cookies to my teachers and my class, and then it was time to get back to work. I didn't arrive home until five, since I went to gym with the rest of the class. (I'm not allowed to take part because my shoulders and hips tend to get dislocated.) As it was my birthday, I got to decide which game my classmates would play, and I chose volleyball.`,

  `Afterward they all danced around me in a circle and sang "Happy Birthday." When I got home, Sanne Ledermann was already there. Ilse Wagner, Hanneli Goslar and Jacqueline van Maarsen came home with me after gym, since we're in the same class. Hanneli and Sanne used to be my two best friends. People who saw us together used to say, "There goes Anne, Hanne and Sanne." I only met Jacqueline van Maarsen when I started at the Jewish Lyceum, and now she's my best friend. Ilse is Hanneli's best friend, and Sanne goes to another school and has friends there.`,
  `Writing in a diary is a really strange experience for someone like me. Not only because I've never written anything before, but also because it seems to me that later on neither I nor anyone else will be interested in the musings of a thirteen-year-old schoolgirl. Oh well, it doesn't matter. I feel like writing, and I have an even greater need to get all kinds of things off my chest.`,

  `"Paper has more patience than people." I thought of this saying on one of those days when I was feeling a little depressed and was sitting at home with my chin in my hands, bored and listless, wondering whether to stay in or go out. I finally stayed where I was, brooding. Yes, paper does have more patience, and since I'm not planning to let anyone else read this stiff-backed notebook grandly referred to as a "diary," unless I should ever find a real friend, it probably won't make a bit of difference.`,

  `Let me put it more clearly, since no one will believe that a thirteen year-old girl is completely alone in the world. And I'm not. I have loving parents and a sixteen-year-old sister, and there are about thirty people I can call friends. I have a throng of admirers who can't keep their adoring eyes off me and who sometimes have to resort to using a broken pocket mirror to try and catch a glimpse of me in the classroom. I have a family, loving aunts and a good home. No, on the surface I seem to have everything, except my one true friend. All I think about when I'm with friends is having a good time.`,
  ` I can't bring myself to talk about anything but ordinary everyday things. We don't seem to be able to get any closer, and that's the problem. Maybe it's my fault that we don't confide in each other. In any case, that's just how things are, and unfortunately they're not liable to change. This is why I've started the diary.`,

  `My father, the most adorable father I've ever seen, didn't marry my mother until he was thirty-six and she was twenty-five. My sister Margot was born in Frankfurt am Main in Germany in 1926. I was born on June 12, 1929. I lived in Frankfurt until I was four. Because we're Jewish, my father immigrated to Holland in 1933, when he became the Managing Director of the Dutch Opekta Company, which manufactures products used in making jam. My mother, Edith Hollander Frank, went with him to Holland in September, while Margot and I were sent to Aachen to stay with our grandmother. Margot went to Holland in December, and I followed in February, when I was plunked down on the table as a birthday present for Margot.`,

  `After May 1940 the good times were few and far between: first there was the war, then the capitulation and then the arrival of the Germans, which is when the trouble started for the Jews. Our freedom was severely restricted by a series of anti-Jewish decrees: Jews were required to wear a yellow star; Jews were required to turn in their bicycles; Jews were forbidden to use street-cars; Jews were forbidden to ride in cars, even their own; Jews were required to do their shopping between 3 and 5 P.M.; Jews were required to frequent only Jewish-owned barbershops and beauty parlors; Jews were forbidden to be out on the streets between 8 P.M. and 6 A.M.; Jews were forbidden to attend theaters, movies or any other forms of entertainment; Jews were forbidden to use swimming pools, tennis courts, hockey fields or any other athletic fields; Jews were forbidden to go rowing; Jews were forbidden to take part in any athletic activity in public; Jews were forbidden to sit in their gardens or those of their friends after 8 P.M.; Jews were forbidden to visit Christians in their homes; Jews were required to attend Jewish schools, etc. You couldn't do this and you couldn't do that, but life went on. Jacque always said to me, "I don't dare do anything anymore, 'cause I'm afraid it's not allowed."`,

  `Dearest Kitty! Let me get started right away; it's nice and quiet now. Father and Mother are out and Margot has gone to play Ping-Pong with some other young people at her friend Trees's. I've been playing a lot of Ping-Pong myself lately. So much that five of us girls have formed a club. It's called "The Little Dipper Minus Two." A really silly name, but it's based on a mistake. We wanted to give our club a special name; and because there were five of us, we came up with the idea of the Little Dipper. We thought it consisted of five stars, but we turned out to be wrong. It has seven, like the Big Dipper, which explains the "Minus Two." Ilse Wagner has a Ping-Pong set, and the Wagners let us play in their big dining room whenever we want. Since we five Ping-Pong players like ice cream, especially in the summer, and since you get hot playing Ping-Pong, our games usually end with a visit to the nearest ice-cream parlor that allows Jews: either Oasis or Delphi. We've long since stopped hunting around for our purses or money -- most of the time it's so busy in Oasis that we manage to find a few generous young men of our acquaintance or an admirer to offer us more ice cream than we could eat in a week.`,

  `Our entire class is quaking in its boots. The reason, of course, is the upcoming meeting in which the teachers decide who'll be promoted to the next grade and who'll be kept back. Half the class is making bets. G.Z. and I laugh ourselves sick at the two boys behind us, C.N. and Jacques Kocernoot, who have staked their entire vacation savings on their bet. From morning to night, it's "You're going to pass, No, I'm not," "Yes, you are," "No, I'm not." Even G.'s pleading glances and my angry outbursts can't calm them down. If you ask me, there are so many dummies that about a quarter of the class should be kept back, but teachers are the most unpredictable creatures on earth. Maybe this time they'll be unpredictable in the right direction for a change. I'm not so worried about my girlfriends and myself.`,

  `In everything he says or does, I can see that Hello is in love with me, and it's kind of nice for a change. Margot would say that Hello is eminently suitable. I think so too, but he's more than that. Mother is also full of praise: "A good-looking boy. Nice and polite." I'm glad he's so popular with everyone. Except with my girlfriends. He thinks they're very childish, and he's right about that. Jacque still teases me about him, but I'm not in love with him. Not really. It's all right for me to have boys as friends. Nobody minds.`,

  `Mother is always asking me who I'm going to marry when I grow up, but I bet she'll never guess it's Peter, because I talked her out of that idea myself, without batting an eyelash. I love Peter as I've never loved anyone, and I tell myself he's only going around with all those other girls to hide his feelings for me. Maybe he thinks Hello and I are in love with each other, which we're not. He's just a friend, or as Mother puts it, a beau.`,

  `It seems like years since Sunday morning. So much has happened it's as if the whole world had suddenly turned upside down. But as you can see, Kitty, I'm still alive, and that's the main thing, Father says. I'm alive all right, but don't ask where or how. You probably don't understand a word I'm saying today, so I'll begin by telling you what happened Sunday afternoon.`,

  `At three o'clock (Hello had left but was supposed to come back later), the doorbell rang. I didn't hear it, since I was out on the balcony, lazily reading in the sun. A little while later Margot appeared in the kitchen doorway looking very agitated. "Father has received a call-up notice from the SS," she whispered. "Mother has gone to see Mr. van Daan" (Mr. van Daan is Father's business partner and a good friend.)`,

  `"Don't open the door!" exclaimed Margot to stop me. But it wasn't necessary, since we heard Mother and Mr. van Daan downstairs talking to Hello, and then the two of them came inside and shut the door behind them. Every time the bell rang, either Margot or I had to tiptoe downstairs to see if it was Father, and we didn't let anyone else in. Margot and I were sent from the room, as Mr. van Daan wanted to talk to Mother alone.`,

  `When she and I were sitting in our bedroom, Margot told me that the call-up was not for Father, but for her. At this second shock, I began to cry. Margot is sixteen -- apparently they want to send girls her age away on their own. But thank goodness she won't be going; Mother had said so herself, which must be what Father had meant when he talked to me about our going into hiding. Hiding. . . where would we hide? In the city? In the country? In a house? In a shack? When, where, how. . . ? These were questions I wasn't allowed to ask, but they still kept running through my mind.`,

  `Margot and I started packing our most important belongings into a schoolbag. The first thing I stuck in was this diary, and then curlers, handkerchiefs, schoolbooks, a comb and some old letters. Preoccupied by the thought of going into hiding, I stuck the craziest things in the bag, but I'm not sorry. Memories mean more to me than dresses.`,

  `Father finally came home around five o'clock, and we called Mr. Kleiman to ask if he could come by that evening. Mr. van Daan left and went to get Miep. Miep arrived and promised to return later that night, taking with her a bag full of shoes, dresses, jackets, underwear and stockings. After that it was quiet in our apartment; none of us felt like eating. It was still hot, and everything was very strange.`,

  `So there we were, Father, Mother and I, walking in the pouring rain, each of us with a schoolbag and a shopping bag filled to the brim with the most varied assortment of items. The people on their way to work at that early hour gave us sympathetic looks; you could tell by their faces that they were sorry they couldn't offer us some kind of transportation; the conspicuous yellow star spoke for itself.`,

  `The hiding place was located in Father's office building. That's a little hard for outsiders to understand, so I'll explain. Father didn't have a lot of people working in his office, just Mr. Kugler, Mr. Kleiman, Miep and a twenty-three-year-old typist named Bep Voskuijl, all of whom were informed of our coming. Mr. Voskuijl, Bep's father, works in the warehouse, along with two assistants, none of whom were told anything.`,

  `Next to the warehouse doors is another outside' door, a separate entrance to the office. Just inside the office door is a second door, and beyond that a stairway. At the top of the stairs is another door, with a frosted window on which the word "Office" is written in black letters. This is the big front office -- very large, very light and very full. Bep, Miep and Mr. Kleiman work there during the day. After passing through an alcove containing a safe, a wardrobe and a big supply cupboard, you come to the small, dark, stuffy back office. This used to be shared by Mr. Kugler and Mr. van Daan, but now Mr. Kugler is its only occupant. Mr. Kugler's office can also be reached from the hallway, but only through a glass door that can be opened from the inside but not easily from the outside. If you leave Mr. Kugler's office and proceed through the long, narrow hallway past the coal bin and go up four steps, you find yourself in the private office, the showpiece of the entire building. Elegant mahogany furniture, a linoleum floor covered with throw rugs, a radio, a fancy lamp, everything first class. Next door is a spacious kitchen with a hot-water heater and two gas burners, and beside that a bathroom. That's the second floor.`,
];

export default sentences;
